### ISSUE TITLE
Update pod list

### ISSUE THREAD

**Issue by ciubotaru** [ciubotaru/share-on-diaspora#35]
This is a recurrent issue, which by definition will never be "solved".

**Comment by gutobenn** [comment]
Generate file with podupti.me data using lynx :
```
lynx -dump -listonly http://podupti.me/ | grep -Po '(?<=domain=)[^ ]*' >> pod_list_all.txt
```

**Comment by Flaburgan** [comment]
You can get a list of diaspora* pods which is more complete than podupti.me here: http://the-federation.info/pods.json
Be sure to filter on the "network" key to only have real diaspora* pods.

**Comment by ciubotaru** [comment]
Oh, great! Thank you!

If the source is reliable enough, it would be nice to integrate it into the plugin, so that blog admins could get the latest list automatically, without updating the pod...

**Comment by Flaburgan** [comment]
I personally chose to let the user enter his diaspora* id for [my Firefox OS app](https://github.com/Flaburgan/diaspora-webapp), there is way too many pods now to list them all in my opinion. Or maybe you can use that to autocomplete.

**Comment by ciubotaru** [comment]
I had a look at http://the-federation.info/pods.json. It looks very promising and I started implementing it. Hoever, most pod's network is marked as "unknown", and only 17 (mostly small pods) are clearly "Diaspora". Maybe the author, @jaywink, can clarify a bit.

**Comment by Flaburgan** [comment]
@ciubotaru this is because the network key was added in the 0.5.0.0 version (currently ".develop"). This version is not released yet so only pods running the develop branch have it. Once the version will be released (we hope around the end of february) every pod will be able to upgrade to 0.5 and then have the network key.

**Comment by jaywink** [comment]
As Fla said, with the next version all those unknowns will be "Diaspora" - most likely at least ;)

**Comment by ciubotaru** [comment]
I see. Thank you for the answers.

**Comment by ciubotaru** [comment]
Update: I wrote a small auxiliary plugin, [Diaspora Podlist Updater](https://github.com/ciubotaru/diaspora-podlist-updater), that daily (via cronjob) downloads a fresh list of active pods from [Podupti.me](Podupti.me). If [the-federation.info](the-federation.info) is more reliable, we can switch to it.

I guess I can close this issue as "solved".
