### ISSUE TITLE
Type error in share-on-diaspora.pot

### ISSUE THREAD

**Issue by georgkrause** [ciubotaru/share-on-diaspora#46]
Not shure if this is correct, but it seems like a type error:

"Check the ones that you what to appear in the drop-down menu in the pod selection window."

i guess it should be:

"Check the ones that you want to appear in the drop-down menu in the pod selection window."

**Comment by ciubotaru** [comment]
Fixed in https://github.com/ciubotaru/share-on-diaspora/commit/bb2634f56b411a9cdfd0766b5881294d13d29c3e (.php and .pot file) and https://github.com/ciubotaru/share-on-diaspora/commit/8c9f6c53120f9cb0f1c94ae9e5d1e6b42287ea84 (.mo files). Closing.

Thank you for the report!
