### ISSUE TITLE
Several warnings on admin page

### ISSUE THREAD

**Issue by JanRei** [ciubotaru/share-on-diaspora#57]
On my development system I am using WordPress 4.2.2 with PHP 5.6.8. After activation of the plugin I get the following warnings. The last three warnings appear now on every page in the admin menu.

> Strict Standards:  call_user_func_array() expects parameter 1 to be a valid callback, non-static method ShareOnDiaspora::plugin_activation() should not be called statically in wordpress\wp-includes\plugin.php on line 496

> Strict Standards:  call_user_func_array() expects parameter 1 to be a valid callback, non-static method ShareOnDiaspora::i18n_init() should not be called statically in wordpress\wp-includes\plugin.php on line 496

> Strict Standards:  call_user_func_array() expects parameter 1 to be a valid callback, non-static method ShareOnDiaspora::register_share_on_diaspora_css() should not be called statically in wordpress\wp-includes\plugin.php on line 496

> PHP Strict Standards:  call_user_func_array() expects parameter 1 to be a valid callback, non-static method ShareOnDiaspora::register_share_on_diaspora_js() should not be called statically in wordpress\wp-includes\plugin.php on line 49

**Comment by ciubotaru** [comment]
Thank you very much for reporting this issue. It has been addressed in https://github.com/ciubotaru/share-on-diaspora/commit/5f4d0b8a3d0cf8b5101199fccffd5e1eff6a1fe6. The fix will be included in the next update.

**Comment by ciubotaru** [comment]
Update: version 0.6.4, which has just been released, includes the fix. Thank you again.
