### ISSUE TITLE
Wordpress 4.7.3 "Error 404 página no encontrada" "Page not found" (SOLVED)

### ISSUE THREAD

**Issue by aldobelus0** [ciubotaru/share-on-diaspora#62]
I have installed the plugin in this version and after put my pod, answer "page doesn't found" Error 404!

I know that I haven't to wait other behaviour from the plugin because is not tested here but I suppose that the info serves you to know about how it is working on different versions.

If doesn't, you can erase the issue.

**Comment by ciubotaru** [comment]
Hm, I can not reproduce this error. I am using version 4.7.3 and the plugin works fine here.
Let's try to find it out together:
1. Can you give me a link to your blog where the error happened AND a link to your Diaspora pod?
2. Did you change any settings (specifically, the "Pod list Optons") in the plugin control panel?

**Comment by aldobelus0** [comment]
https://colaboratorio.net/
https://wk3.org
I didn't changed anything at the podlist options. I have tipped everything you told me and the answer is the same one.
This one: 
![error-diaspora](https://cloud.githubusercontent.com/assets/15985449/23803524/1cbe9756-05b7-11e7-98d7-b3d5125bec30.png)

**Comment by ciubotaru** [comment]
Thank you for your answers and for the screenshot. I still can not reproduce the bug, though. I went to you blog (colaboratorio.net), opened an article, clicked on "Share this", typed a pod address (wk3.com) and it worked fine. No idea.

**Comment by aldobelus0** [comment]
I have, finally, found the responsible for this behaviour, ciubotaru. This is the one:
https://addons.mozilla.org/en-US/firefox/addon/random-agent-spoofer/ 
or this other one, which is the same one:
https://github.com/dillbyrne/random-agent-spoofer
When I have had the time to test your plugin I did the regular process: disconnect extensions one by one, till find the guilty. 

So, now, it works perfectly! I'm sorry for the alarm but you have more info now, right? This is the right way, ask and solve the problems. 

Greetings! (and congrats for your plugin)...

**Comment by ciubotaru** [comment]
Closing.
