### ISSUE TITLE
Can not edit posts since wordpress update 5.0

### ISSUE THREAD

**Issue by paidge** [ciubotaru/share-on-diaspora#65]
Hi, when the plugin is activated, I can not edit the posts anymore since the last wordpress update. For instance, the url https://my-domain.com/wp-admin/post.php?post=78&action=edit returns no HTML. The source code of the returned page is empty.

**Comment by ciubotaru** [comment]
Thank you very much for reporting this. I have just checked the plugin with the latest version (5.0.1) of Wordpress and I confirm the bug.

**Comment by ciubotaru** [comment]
I can not promise to fix it quickly, so any person reading this is welcome to contribute a patch.

**Comment by paidge** [comment]
I'm a noob with git and I'm not a good PHP developper but I tried to solve the problem. I don't know if it is a good solution but [here is a commit](https://github.com/paidge/share-on-diaspora/commit/a7407f5d1c5eac910c63ab282705a28676016ea6) that I did and which has solved the problem on my server.

**Comment by ciubotaru** [comment]
Thank you very much! I really appreciate your effort. Your code has been merged into unstable (https://github.com/ciubotaru/share-on-diaspora/commit/fee38118067d42e712ce3ee7c0a542881167802b) and will be released soon. Basically, my role is just to close the issue :-)
