### ISSUE TITLE
My posts are share twice on my diaspora account

### ISSUE THREAD

**Issue by paidge** [ciubotaru/share-on-diaspora#66]
Happy New Year and a very big THX for your work. Before he 5.0 version of wordpress the plugin worked fine. But I just noticed that my posts are shared twice on my D* account with the 5.0.2 version of Wordpress.

**Comment by ciubotaru** [comment]
Happy New Year to you, too!

Thank you very much for reporting this issue. Frankly speaking, I don't understand how it can happen at all. I mean, the plugin does not post directly to Diaspora. Instead:
- pressing the "Share" button below a WordPress post brings up a dialog window
- here the user chooses his/her preferred Diaspora pod and presses another "Share" button
- Diaspora pod opens a so-called "bookmarklet" window, where the user can edit his post, choose the desired aspects etc. and finally press "Share"
- Diaspora pod adds the post and the link to user's stream.

From these four points only the first two (displaying the share button under the WordPress article and displaying the pod selection dialog) are performed by this plugin. The last two actions are performed by Diaspora pod and are out of our control.

Now I would like to know where exactly this duplication happens. You see one "Share" button, you see one pod-selection dialog, you see one bookmarklet window and then you see two identical posts in your diaspora stream -- is that right?

**Comment by ciubotaru** [comment]
Update: I can not reproduce this with the latest version (5.0.2) of WordPress. Are you using any other sharing plugins (e.g. "[WP to Diaspora](https://wordpress.org/plugins/wp-to-diaspora/)"), that might have caused this duplication?

**Comment by paidge** [comment]
Indeed, that's "WP to Diaspora" which is having problems. I thought I was on the good repository.... I'm very confused to have made you waste your time
