### ISSUE TITLE
Version 0.7.7 not compatible with wordpress v5.2

### ISSUE THREAD

**Issue by paidge** [ciubotaru/share-on-diaspora#67]
Hi.
Since the last update, i can not edit my posts anymore if the plugin is activated. Wordpress sent me an email to confirm that the plugin "Share on Diaspora*" was the origin of the problem when I wanted to edit a post.

**Comment by ciubotaru** [comment]
Thank you for you report.

I can confirm the bug. Please update to 0.7.8 and check if the problem is solved.

**Comment by paidge** [comment]
Thanks :) This new version solved the problem.
